// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AutoclickController from "./autoclick_controller"
application.register("autoclick", AutoclickController)

import CliqController from "./cliq_controller"
application.register("cliq", CliqController)

import FormController from "./form_controller"
application.register("form", FormController)

import SearchController from "./search_controller"
application.register("search", SearchController)
