Profile.create!([
  {user_id: 1, username: "ricky"}
])
Post.create!([
  {title: "Cliq Bait number 6-788b", content: "Do we really gotta?", cliq_id: 5, user_id: 1, slug: "cliq-bait-number-6-7"},
  {title: "Cliq Bait number 7-cb6d", content: "Do we really gotta?", cliq_id: 5, user_id: 1, slug: "cliq-bait-number-7-c"},
  {title: "Cliq Bait number 8-7c7e", content: "Do we really gotta?", cliq_id: 5, user_id: 1, slug: "cliq-bait-number-8-7"},
  {title: "Cliq Bait number 9-4903", content: "Do we really gotta?", cliq_id: 5, user_id: 1, slug: "cliq-bait-number-9-4"},
  {title: "Cliq Bait number 10-1af6", content: "Do we really gotta?", cliq_id: 5, user_id: 1, slug: "cliq-bait-number-10"},
  {title: "Cliq Bait number 11-0734", content: "Do we really gotta?", cliq_id: 5, user_id: 1, slug: "cliq-bait-number-11"},
  {title: "Cliq Bait number 12-7185", content: "Do we really gotta?", cliq_id: 5, user_id: 1, slug: "cliq-bait-number-12"},
  {title: "Cliq Bait number 13-3c39", content: "Do we really gotta?", cliq_id: 5, user_id: 1, slug: "cliq-bait-number-13"},
  {title: "Cliq Bait number 14-3597", content: "Do we really gotta?", cliq_id: 5, user_id: 1, slug: "cliq-bait-number-14"},
  {title: "Cliq Bait number 15-5a3e", content: "Do we really gotta?", cliq_id: 5, user_id: 1, slug: "cliq-bait-number-15"},
  {title: "Cliq Bait number 16-95c4", content: "Do we really gotta?", cliq_id: 5, user_id: 1, slug: "cliq-bait-number-16"},
  {title: "Cliq Bait number 17-e224", content: "Do we really gotta?", cliq_id: 5, user_id: 1, slug: "cliq-bait-number-17"},
  {title: "General Gaming Post", content: "Test", cliq_id: 7, user_id: 1, slug: "general-gaming-post"},
  {title: "Another General Post", content: "asd asd", cliq_id: 7, user_id: 1, slug: "another-general-post"},
  {title: "Aurora B in the sky", content: "ok", cliq_id: 4, user_id: 1, slug: "aurora-b-in-the-sky"},
  {title: "I hate politics", content: "you should", cliq_id: 5, user_id: 1, slug: "i-hate-politics"},
  {title: "I also hate politics", content: "everyone should", cliq_id: 5, user_id: 1, slug: "i-also-hate-politics"},
  {title: "Astro Bot is cool", content: "Yes sir ee", cliq_id: 9, user_id: 1, slug: "astro-bot-is-cool"},
  {title: "New NEws Post for gaming", content: "testing", cliq_id: 14, user_id: 1, slug: "new-news-post-for-ga"},
  {title: "What about Hollywood?", content: "Is it still around?", cliq_id: 1, user_id: 1, slug: "what-about-hollywood"},
  {title: "That new movie is coming out", content: "Cool", cliq_id: 15, user_id: 1, slug: "that-new-movie-is-co"},
  {title: "Oceans are cool", content: "and big", cliq_id: 19, user_id: 1, slug: "oceans-are-cool"},
  {title: "Trees are green", content: "And different in autumn", cliq_id: 18, user_id: 1, slug: "trees-are-green"},
  {title: "Breaking! Slugs are not games", content: "OK", cliq_id: 14, user_id: 1, slug: "breaking-slugs-are"},
  {title: "New politics post", content: "include slugs", cliq_id: 5, user_id: 1, slug: "new-politics-post"},
  {title: "Until Dawn Remake", content: "Overly Expensive Rip Off", cliq_id: 9, user_id: 1, slug: "until-dawn-remake"},
  {title: "System105 is blamo!", content: "Wooo", cliq_id: 23, user_id: 1, slug: "system105-is-blamo"},
  {title: "Did you hear about this system", content: "no?", cliq_id: 23, user_id: 1, slug: "did-you-hear-about-t"},
  {title: "Oh, its fake?", content: "yes", cliq_id: 23, user_id: 1, slug: "oh-its-fake"},
  {title: "Wait .. Are you sure? I heard more", content: "no .. its still fake", cliq_id: 23, user_id: 1, slug: "wait-are-you-sure"},
  {title: "Does anyone actually own one of these?", content: "What games are cool?", cliq_id: 11, user_id: 1, slug: "does-anyone-actually"},
  {title: "Hey - I still have an xbox", content: "Im cool (no im not)", cliq_id: 11, user_id: 1, slug: "hey-i-still-have-a"},
  {title: "Trees are so big", content: "Yes", cliq_id: 18, user_id: 1, slug: "trees-are-so-big"},
  {title: "I chop trees down", content: "so i can eat", cliq_id: 18, user_id: 1, slug: "i-chop-trees-down"},
  {title: "Trees are blue", content: "No they aren't you dummie", cliq_id: 18, user_id: 1, slug: "trees-are-blue"},
  {title: "Politicians are stupid eddit", content: "youre right", cliq_id: 5, user_id: 1, slug: "politicians-are-stup"},
  {title: "Did you see that interview? yesterday", content: "Who cares right?", cliq_id: 5, user_id: 1, slug: "did-you-see-that-int"},
  {title: "Cliq Bait number 0-d64a", content: "Do we really gotta?", cliq_id: 5, user_id: 1, slug: "cliq-bait-number-0-d"},
  {title: "Cliq Bait number 1-cc8a", content: "Do we really gotta?", cliq_id: 5, user_id: 1, slug: "cliq-bait-number-1-c"},
  {title: "Cliq Bait number 2-a02e", content: "Do we really gotta?", cliq_id: 5, user_id: 1, slug: "cliq-bait-number-2-a"},
  {title: "Cliq Bait number 3-d953", content: "Do we really gotta?", cliq_id: 5, user_id: 1, slug: "cliq-bait-number-3-d"},
  {title: "Cliq Bait number 4-b084", content: "Do we really gotta?", cliq_id: 5, user_id: 1, slug: "cliq-bait-number-4-b"},
  {title: "Cliq Bait number 5-2f99", content: "Do we really gotta?", cliq_id: 5, user_id: 1, slug: "cliq-bait-number-5-2"},
  {title: "Cliq Bait number 18-85ab", content: "Do we really gotta?", cliq_id: 5, user_id: 1, slug: "cliq-bait-number-18"},
  {title: "Cliq Bait number 19-c67f", content: "Do we really gotta?", cliq_id: 5, user_id: 1, slug: "cliq-bait-number-19"},
  {title: "Cliq Bait number 20-2d28", content: "Do we really gotta?", cliq_id: 5, user_id: 1, slug: "cliq-bait-number-20"},
  {title: "Cliq Bait number 21-bba8", content: "Do we really gotta?", cliq_id: 5, user_id: 1, slug: "cliq-bait-number-21"},
  {title: "Cliq Bait number 22-8f76", content: "Do we really gotta?", cliq_id: 5, user_id: 1, slug: "cliq-bait-number-22"},
  {title: "Cliq Bait number 23-6c38", content: "Do we really gotta?", cliq_id: 5, user_id: 1, slug: "cliq-bait-number-23"},
  {title: "Cliq Bait number 24-7a20", content: "Do we really gotta?", cliq_id: 5, user_id: 1, slug: "cliq-bait-number-24"},
  {title: "Cliq Bait number 25-24ff", content: "Do we really gotta?", cliq_id: 5, user_id: 1, slug: "cliq-bait-number-25"},
  {title: "Cliq Bait number 26-3436", content: "Do we really gotta?", cliq_id: 5, user_id: 1, slug: "cliq-bait-number-26"},
  {title: "Cliq Bait number 27-b8f5", content: "Do we really gotta?", cliq_id: 5, user_id: 1, slug: "cliq-bait-number-27"},
  {title: "Cliq Bait number 28-3a3a", content: "Do we really gotta?", cliq_id: 5, user_id: 1, slug: "cliq-bait-number-28"},
  {title: "Cliq Bait number 29-c728", content: "Do we really gotta?", cliq_id: 5, user_id: 1, slug: "cliq-bait-number-29"},
  {title: "Cliq Bait number 30-ee49", content: "Do we really gotta?", cliq_id: 5, user_id: 1, slug: "cliq-bait-number-30"},
  {title: "Cliq Bait number 31-fd26", content: "Do we really gotta?", cliq_id: 5, user_id: 1, slug: "cliq-bait-number-31"},
  {title: "Cliq Bait number 32-bacb", content: "Do we really gotta?", cliq_id: 5, user_id: 1, slug: "cliq-bait-number-32"},
  {title: "Cliq Bait number 33-2170", content: "Do we really gotta?", cliq_id: 5, user_id: 1, slug: "cliq-bait-number-33"},
  {title: "Cliq Bait number 34-89a3", content: "Do we really gotta?", cliq_id: 5, user_id: 1, slug: "cliq-bait-number-34"},
  {title: "Cliq Bait number 35-690e", content: "Do we really gotta?", cliq_id: 5, user_id: 1, slug: "cliq-bait-number-35"},
  {title: "Cliq Bait number 36-83e3", content: "Do we really gotta?", cliq_id: 5, user_id: 1, slug: "cliq-bait-number-36"},
  {title: "Cliq Bait number 37-9e61", content: "Do we really gotta?", cliq_id: 5, user_id: 1, slug: "cliq-bait-number-37"},
  {title: "Cliq Bait number 38-cfc0", content: "Do we really gotta?", cliq_id: 5, user_id: 1, slug: "cliq-bait-number-38"},
  {title: "Cliq Bait number 39-9a00", content: "Do we really gotta?", cliq_id: 5, user_id: 1, slug: "cliq-bait-number-39"},
  {title: "Cliq Bait number 40-c017", content: "Do we really gotta?", cliq_id: 5, user_id: 1, slug: "cliq-bait-number-40"},
  {title: "Cliq Bait number 41-20f3", content: "Do we really gotta?", cliq_id: 5, user_id: 1, slug: "cliq-bait-number-41"},
  {title: "Cliq Bait number 42-f7ba", content: "Do we really gotta?", cliq_id: 5, user_id: 1, slug: "cliq-bait-number-42"},
  {title: "Cliq Bait number 43-7cf3", content: "Do we really gotta?", cliq_id: 5, user_id: 1, slug: "cliq-bait-number-43"},
  {title: "Cliq Bait number 44-5fa5", content: "Do we really gotta?", cliq_id: 5, user_id: 1, slug: "cliq-bait-number-44"},
  {title: "Cliq Bait number 45-b1f2", content: "Do we really gotta?", cliq_id: 5, user_id: 1, slug: "cliq-bait-number-45"},
  {title: "Cliq Bait number 46-d0d1", content: "Do we really gotta?", cliq_id: 5, user_id: 1, slug: "cliq-bait-number-46"},
  {title: "Cliq Bait number 47-8c21", content: "Do we really gotta?", cliq_id: 5, user_id: 1, slug: "cliq-bait-number-47"},
  {title: "Cliq Bait number 48-a639", content: "Do we really gotta?", cliq_id: 5, user_id: 1, slug: "cliq-bait-number-48"},
  {title: "Cliq Bait number 49-e500", content: "Do we really gotta?", cliq_id: 5, user_id: 1, slug: "cliq-bait-number-49"},
  {title: "Hey - I still have an xbox", content: "Can you believe it? A repeat title", cliq_id: 7, user_id: 1, slug: "hey-i-still-have-a-b4adf4dd-d93d-4121-b13c-11f3f533c081"},
  {title: "Hey - I still have an xbox", content: "Yet another dork who has an xbox", cliq_id: 7, user_id: 1, slug: "hey-i-still-have-a-f0a992fe-7281-403f-b879-9d5a2e284d3e"},
  {title: "Random new Politics Post", content: "erheajlsd", cliq_id: 5, user_id: 1, slug: "random-new-politics"},
  {title: "Rivers all run down", content: "unless they go up", cliq_id: 20, user_id: 1, slug: "rivers-all-run-down"},
  {title: "This system is fake", content: "booyah", cliq_id: 26, user_id: 1, slug: "this-system-is-fake"},
  {title: "Need a post for Republicans", content: "Because they suck, and so do democrats", cliq_id: 12, user_id: 1, slug: "need-a-post-for-repu"},
  {title: "Nintendo has weak systems", content: "But good gamess", cliq_id: 21, user_id: 1, slug: "nintendo-has-weak-sy"},
  {title: "Lots of Celebs moving away right?", content: "Or maybe just Ellen", cliq_id: 1, user_id: 1, slug: "lots-of-celebs-movin"},
  {title: "New Enter", content: "Bout to watch a movie", cliq_id: 1, user_id: 1, slug: "new-enter"},
  {title: "The Summit", content: "My Wife likes this for some reason", cliq_id: 28, user_id: 1, slug: "the-summit"}
])
Cliq.create!([
  {name: "AstroBot", description: nil, parent_cliq_id: 9, slug: "9-astrobot"},
  {name: "Fake", description: nil, parent_cliq_id: 23, slug: "23-fake"},
  {name: "TV Shows", description: nil, parent_cliq_id: 1, slug: "1-tv-shows"},
  {name: "The Summit", description: nil, parent_cliq_id: 27, slug: "27-the-summit"},
  {name: "Rivers", description: nil, parent_cliq_id: 4, slug: "4-rivers"},
  {name: "Cliq", description: nil, parent_cliq_id: nil, slug: "cliq"},
  {name: "Playstation 5", description: nil, parent_cliq_id: 7, slug: "7-playstation-5"},
  {name: "PC", description: nil, parent_cliq_id: 7, slug: "7-pc"},
  {name: "Xbox", description: nil, parent_cliq_id: 7, slug: "7-xbox"},
  {name: "Republicans", description: nil, parent_cliq_id: 5, slug: "5-republicans"},
  {name: "News", description: nil, parent_cliq_id: 7, slug: "7-news"},
  {name: "Movies", description: nil, parent_cliq_id: 1, slug: "1-movies"},
  {name: "News", description: nil, parent_cliq_id: 9, slug: "9-news"},
  {name: "Computers", description: nil, parent_cliq_id: 4, slug: "4-computers"},
  {name: "Trees", description: nil, parent_cliq_id: 4, slug: "4-trees"},
  {name: "Oceans", description: nil, parent_cliq_id: 4, slug: "4-oceans"},
  {name: "Entertainment", description: "All your entertainment needs here.  Drill down to discuss specific interests!", parent_cliq_id: 8, slug: "entertainment"},
  {name: "Science", description: nil, parent_cliq_id: 8, slug: "science"},
  {name: "Gaming", description: nil, parent_cliq_id: 8, slug: "gaming"},
  {name: "Politics", description: nil, parent_cliq_id: 8, slug: "politics"},
  {name: "Nintendo", description: nil, parent_cliq_id: 14, slug: "14-nintendo"},
  {name: "Books", description: nil, parent_cliq_id: 1, slug: "1-books"},
  {name: "System105", description: nil, parent_cliq_id: 7, slug: "7-system105"},
  {name: "Leaves", description: nil, parent_cliq_id: 18, slug: "18-leaves"}
])
User.create!([
  {email: "rickymm3@gmail.com", encrypted_password: "$2a$12$GYplgI/ZIzUL885n62IcMe4BDfRmwO.bXsMn2keFCNMPX8qkxoQPa", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, username: "Rickymm3"}
])
